name: Called Workflow
on: workflow_dispatch
  
jobs:
  Echo-Message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow was triggered by the Trigger Workflow and Wait GitHub Action 🎉"
      - run: sleep 10s
      # - run: exit 1
  Second-Concurrent-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second Concurrent Job is running..."
      - run: sleep 10s
